### ISSUE TITLE
Add OpRet commitments to the library

### ISSUE THREAD

**Issue by dr-orlovsky** [BP-WG/bp-core#28]
@zoedberg: can you please move the current implementation of the opret commitments in RGB here? I can't find in which library they do exist today, and I think they must be happening in the same place as tapret commitments (i.e. in this library).

**Comment by zoedberg** [comment]
sure, I'll be happy to do that right after 0.8.x milestone will be completed

**Comment by dr-orlovsky** [comment]
Thank you. I think it will be nice to move opret to the consensus-level as a part of 0.8.1 to have the same review rules applying to the consensus-critical code. For now I haven't even seen how opret commitments are constructed.

**Comment by zoedberg** [comment]
@dr-orlovsky Ok, I'll try to do it. I hope it will not break other projects, otherwise I'll let you know and we'll see what we can do. Could you please move this to the 0.8 milestone?

**Comment by zoedberg** [comment]
Hi @dr-orlovsky. I started looking into the details of this issue, but as far as I understood all code related to opret is already in bp-core.

From rgb-lib the only objects related to opret that we use are `CloseMethod::OpretFirst`, which is defined in [`seals/src/txout/seal.rs`](https://github.com/BP-WG/bp-core/blob/master/seals/src/txout/seal.rs#L60) and the [`Output::set_opret_host`](https://github.com/BP-WG/descriptor-wallet/blob/master/psbt/src/commit/opret.rs#L97) method from descriptor-wallet. The latter should be the equivalent of [`Output::set_tapret_dfs_path`](https://github.com/BP-WG/descriptor-wallet/blob/master/psbt/src/commit/tapret.rs#L149), so I guess it's correct for it to stay there.

Then in bp-core repo you can also find a `Proof::OpretFirst` object in [`dbc/src/anchor.rs`](https://github.com/BP-WG/bp-core/blob/master/dbc/src/anchor.rs#L416).

Cannot find other code related to opret in other repositories, so I guess this issue can be closed and you can review what's has been implemented in bp-core.

I found 2 commits of yours related to opret: [Implement anchor commitments from PSBT data](https://github.com/BP-WG/bp-core/commit/900bbd4d17cc91cd1d0f86391c4be9ac6b23855b) and [Opret commitment "proof" verification](https://github.com/BP-WG/bp-core/commit/87d5ef3e439c7d1e1e0fcab76802d9add278a97f), not sure but they may help refresh your memory.

**Comment by dr-orlovsky** [comment]
Thank you for the very detailed explanations.

My thought was that the most consensus- and compatibility-critical part of the whole OpRet story is how exactly we structure the OP_RETURN `scriptPubkey`: which specific hash, with which tag gets in there.

I propose to add OpRet construction as a method to the `ScriptPubkey` object coming from the `bitcoin_script` library - and have it in this lib.

I can do it myself, I just need the information on how the OP_RETURN is constructed in your code.

**Comment by zoedberg** [comment]
> I can do it myself, I just need the information on how the OP_RETURN is constructed in your code.

Not sure what you intend, we do not construct OP_RETURN directly. The opret-related calls we do in rgb-lib are those that I've mentioned, more precisely:

```rust
// when creating blinded UTXO
let seal = seal::Revealed::new(CloseMethod::OpretFirst, OutPoint::from(utxo.clone()));

// revealed_seal contains an ExplicitSeal with CloseMethod::OpretFirst
rgb_asset.transfer(input_outpoints_bt.clone(), beneficiaries, revealed_seal)

// new_outpoints contains CloseMethod::OpretFirst
let blank_bundle = TransitionBundle::blank(&outpoint_map, &new_outpoints)

// after bundle and before transfer finalize
psbt.outputs
    .last_mut()
    .expect("PSBT should have outputs")
    .set_opret_host()

// reveal contains CloseMethod::OpretFirst
.consume_transfer(consignment, true, reveal, |_| ())
```

That's all, everything else is constructed the same as with tapret.

**Comment by dr-orlovsky** [comment]
Hm, very strange. Thank you. Can't recall where in my code I was constructing - or validating - the OP_RETURN `scriptPubkey` with the commitment hash...

**Comment by dr-orlovsky** [comment]
In https://github.com/RGB-WG/rgb-wallet/pull/23 I checked that in the library we have everything needed for the opret commitments
