### ISSUE TITLE
TxStatus

### ISSUE THREAD

**Issue by cryptoquick** [BP-WG/bp-core#73]
In bp-esplora-client, there's a TxStatus type, but it's slightly different than the one used in bp-wallet. Compare:

https://github.com/BP-WG/bp-esplora-client/blob/689eb8f93282c69a77c98f878492f0726c5d5fe4/src/api.rs#L46-L52

And:

https://github.com/BP-WG/bp-wallet/blob/e8aa19d8475b14392ae7f1d9dfad1f41e0690056/src/data.rs#L95-L130

The bp-wallet enum has the same data, but it's a slightly different type. I actually prefer the richer type. Should we include it in bp-core so we can use it in both bp-wallet and bp-esplora-client?

If so, where should it go?

**Comment by dr-orlovsky** [comment]
These two types, while having the same name, has very different semantic meaning. The one indicated the height where the tx is mined and can be applied to a non-mined, the other provides extra details for only mined transaction. Basically, you can wrap one into another.

So the solution will be to rename one of them and keep both

**Comment by dr-orlovsky** [comment]
Oh actually the esplora has to match esplora API and it has this strange decision to use plenty of optionals instead of one. So it is clearly specific to that crate and should not be put outside of it

**Comment by cryptoquick** [comment]
The optionals are just because of the type behavior, and it's poor design compared to the actual idiom it should be expressing, which is better expressed as enums. I'm proposing that bp-esplora-client use the enum-based approach taken in bp-wallet instead of its own legacy type, and then we just use the same TxStatus.

**Comment by cryptoquick** [comment]
Okay, that reasoning makes sense. If that's how it should be, the main reason I opened this issue was because we had to write some code to translate from the one type to the other. I can open a PR with a function that at least adds that code so others can make use of it also.
